version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION> 
        LoadBalancerInfo:
          ContainerName: "oneapp-ux-api-1"
          ContainerPort: 3000
