version: "3.0"
services:
  oneapp-ux-api-1:
    build: ./
    image: oneapp-ux-api-1
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - default
networks:
  default:
